### ISSUE TITLE
debriefing

### ISSUE THREAD

**Issue by HjalmarSnoep** [Traxx186/myBand#1]
Hoi Justin,

Prima debriefing, twee puntjes:

- let op spelling
-je zegt een aantal keer wij. Het is een individueel project!

Onderwerp train-simulator is goedgekeurd.
Moderation van comments is ambitieuzer dan gevraagd, maar ik denk wel interessant. Maak het geen prioriteit, maar als je alle verplichte figuren hebt, GO!

**Comment by Traxx186** [comment]
Ik heb de spelling aangepast
